[package]
name = "tui_bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_common_assets = { version = "0.11.0", features = ["json"] }
bevy = { version = "0.14.2", default-features = false, features = [
  "bevy_state",
  "multi_threaded",
  "async-io",
] }
log = { version = "*", features = [
  "max_level_debug",
  "release_max_level_info",
] }
better-panic = "0.3.0"
delegate = "0.13.0"
ratatui = "0.28.0"
serde = "1.0.210"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"
