[package]
name = "tui_bevy"
version = "0.1.0"
edition = "2021"

[dependencies.bevy]
version = "0.14.1"
default-features = false
features = ["dynamic_linking", "multi_threaded", "async-io"]

[dependencies.log]
version = "*"
features = ["max_level_debug", "release_max_level_warn"]

[dependencies]
delegate = "0.12.0"
ratatui = "0.28.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"
